# Simulation/environment parameters
simulation:
  rng_seed: 1234  # Random seed for reproducibility
  print_time: true  # Print simulation progress (true/false)
  total_num_virtual_procs: 4  # Number of virtual processes for NEST
  step: 1.0  # Simulation time step (ms)

# Task/experiment setup parameters
task:
  n_batch: 1  # Number of batches per training iteration
  n_iter: 100  # Number of training iterations
  sequence: 650  # Sequence length (steps); duration in ms
  offset_gen: 1  # Input generator offset (steps); duration in ms = offset_gen * step
  delay_in_rec: 1  # Input to recurrent delay (steps); duration in ms = delay_in_rec * step
  delay_rec_out: 1  # Recurrent to output delay (steps); duration in ms = delay_rec_out * step
  delay_out_norm: 1  # Output normalization delay (steps); duration in ms = delay_out_norm * step
  extension_sim: 1  # Simulation extension (steps); duration in ms = extension_sim * step
  n_samples: 1 # Number of samples

# RBF encoding parameters
rbf:
  num_centers: 10  # Number of RBF centers for input encoding
  width: 0.25  # RBF width (rad)
  scale_rate: 300.0  # RBF output scaling factor (Hz)

# Neuron parameters
neurons:
  n_rec: 100  # Number of recurrent neurons
  n_out: 2  # Number of output neurons
  exc_ratio: 0.8  # Fraction of excitatory neurons in recurrent population
  rec:
    C_m: 250.0  # Membrane capacitance (pF)
    c_reg: 300.0  # Regularization constant
    E_L: 0.0  # Resting membrane potential (mV)
    f_target: 10.0  # Target firing rate (Hz)
    gamma: 0.3  # Learning rate scaling factor
    I_e: 0.0  # External current (pA)
    regular_spike_arrival: false  # Use regular spike arrival (true/false)
    surrogate_gradient_function: piecewise_linear  # Surrogate gradient function
    t_ref: 2.0  # Refractory period (ms)
    tau_m: 20.0  # Membrane time constant (ms)
    V_m: 0.0  # Initial membrane potential (mV)
    V_th: 20.0  # Spike threshold (mV)
  out:
    C_m: 250.0  # Membrane capacitance (pF)
    E_L: 0.0  # Resting membrane potential (mV)
    I_e: 0.0  # External current (pA)
    loss: mean_squared_error  # Loss function for output neurons
    regular_spike_arrival: false  # Use regular spike arrival (true/false)
    tau_m: 20.0  # Membrane time constant (ms)
    V_m: 0.0  # Initial membrane potential (mV)

# Synapse parameters
synapses:
  w_input: 100.0  # Default synaptic weight (pA)
  w_rec: 100.0  # Recurrent synaptic weight (pA)
  g: 4.0  # Inhibitory/excitatory weight ratio
  conn_bernoulli_p: 0.1  # Connection probability for recurrent connections
  average_gradient: false  # Average gradient across batch (true/false)
  static_delay: 1.0  # Delay for static synapses (ms)
  feedback_delay: 1.0  # Delay for feedback synapses (ms)
  rate_target_delay: 1.0  # Delay for rate target synapses (ms)
  receptor_type: 2  # Receptor type for rate target synapses
  input_weight_mean: 100.0  # Mean initial input synaptic weight (pA)
  input_weight_std: 10.0  # Stddev initial input synaptic weight (pA)

  exc:
    optimizer:
      type: gradient_descent  # Optimizer type
      eta: 0.01  # Learning rate for optimizer
      Wmin: 0.0  # Minimum excitatory weight (pA)
      Wmax: 1000.0  # Maximum excitatory weight (pA)

  inh:
    optimizer:
      type: gradient_descent  # Optimizer type
      eta: 0.01  # Learning rate for optimizer
      Wmin: -1000.0  # Minimum inhibitory weight (pA)
      Wmax: 0.0  # Maximum inhibitory weight (pA)
    weight: -400.0  # Initial inhibitory synaptic weight (pA), will be overwritten

# Recording parameters
recording:
  n_record: 2  # Number of neurons to record
  n_record_w: 5  # Number of weights to record
  mm_rec:
    interval: 1.0  # Recording interval (ms)
    record_from: [V_m, surrogate_gradient, learning_signal]  # Variables to record from recurrent neurons
  mm_out:
    interval: 1.0  # Recording interval (ms)
    record_from: [V_m, readout_signal, readout_signal_unnorm, target_signal, error_signal]  # Variables to record from output neurons

# Plotting
plotting:
  do_plotting: true  # Enable or disable plotting
