[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "motor_controller_model"
version = "0.1.0"
description = "Motor controller model package"
authors = [
    { name = "Renan O. Shimoura" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "pyyaml",
    "pydantic>=2.0",
    "h5py",
    "structlog",
    "minjerk-dynamics"
]

[project.optional-dependencies]
standalone = [
    "nestml",
]
notebook = ["jupyterlab"]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
